DROP TABLE IF EXISTS voting;
DROP TABLE IF EXISTS dishes;
DROP TABLE IF EXISTS menu;
DROP TABLE IF EXISTS restaurants;
DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS users;

DROP SEQUENCE IF EXISTS global_seq;
CREATE SEQUENCE GLOBAL_SEQ AS INTEGER START WITH 100000;

CREATE TABLE users
(
  id               INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  name             VARCHAR(255)                 NOT NULL,
  email            VARCHAR(255)                 NOT NULL,
  password         VARCHAR(255)                 NOT NULL
);
CREATE UNIQUE INDEX users_unique_email_idx ON users (email);

CREATE TABLE user_roles
(
  user_id         INTEGER                 NOT NULL,
  role            VARCHAR(255),
  CONSTRAINT user_roles_idx UNIQUE (user_id, role),
  FOREIGN KEY (user_id) REFERENCES users (id) MATCH FULL ON DELETE CASCADE
);

CREATE TABLE restaurants(
  id              INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  name            VARCHAR(255)                 NOT NULL
);
CREATE UNIQUE INDEX restaurants_unique_name_idx ON restaurants (name);

CREATE TABLE menu(
  id              INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  date            TIMESTAMP               NOT NULL,
  restaurant_id   INTEGER                 NOT NULL,
  FOREIGN KEY (restaurant_id) REFERENCES restaurants (id) MATCH FULL ON DELETE CASCADE
);
CREATE UNIQUE INDEX menu_unique_restaurant_date_idx ON menu (restaurant_id, date);

CREATE TABLE dishes(
  id              INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  name            VARCHAR(255)            NOT NULL,
  price           INTEGER                 NOT NULL,
  menu_id         INTEGER                 NOT NULL,
  FOREIGN KEY (menu_id) REFERENCES menu (id) MATCH FULL ON DELETE CASCADE,
  CONSTRAINT dishes_price_check CHECK (price <= 1000000 AND price >= 0)
);
CREATE UNIQUE INDEX dishes_unique_menu_name_idx ON dishes (menu_id, name);


CREATE TABLE voting(
  id              INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  user_id         INTEGER                 NOT NULL,
  date            TIMESTAMP               NOT NULL,
  menu_id         INTEGER                 NOT NULL,
  FOREIGN KEY (menu_id) REFERENCES public.menu (id) MATCH FULL ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES public.users (id) MATCH FULL ON DELETE CASCADE
);
CREATE UNIQUE INDEX voting_unique_user_date_idx ON voting (user_id, date);
